# -*- coding: utf-8 -*-
"""Tipos de datos_Identificadores

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qdoWemlpyy9yqKPQl1nL6UokKSgbO6mL
"""

# Descripción del programa:
# Este programa solicita al usuario la longitud y el ancho de un rectángulo,
# y luego calcula e imprime su área y perímetro.

def calcular_dimensiones_rectangulo():
    """Calcula el área y el perímetro de un rectángulo basado en la entrada del usuario."""

    # Variable booleana para controlar el bucle de entrada de datos
    entrada_valida = False
    longitud_rectangulo = 0.0
    ancho_rectangulo = 0.0

    while not entrada_valida:
        try:
            # Solicitar la longitud del rectángulo como string y convertir a float
            longitud_str = input("Por favor, introduce la longitud del rectángulo: ")
            longitud_rectangulo = float(longitud_str)

            # Solicitar el ancho del rectángulo como string y convertir a float
            ancho_str = input("Por favor, introduce el ancho del rectángulo: ")
            ancho_rectangulo = float(ancho_str)

            # Validar que las dimensiones sean positivas
            if longitud_rectangulo > 0 and ancho_rectangulo > 0:
                entrada_valida = True
            else:
                print("Error: La longitud y el ancho deben ser números positivos. Inténtalo de nuevo.")
        except ValueError:
            # Manejar el error si la conversión a float falla
            print("Error: Entrada inválida. Por favor, introduce números para la longitud y el ancho.")

    # Calcular el área (tipo de dato: float)
    area_rectangulo = longitud_rectangulo * ancho_rectangulo

    # Calcular el perímetro (tipo de dato: float)
    perimetro_rectangulo = 2 * (longitud_rectangulo + ancho_rectangulo)

    # Imprimir los resultados utilizando f-strings para un formato claro
    print(f"\nResultados para un rectángulo con longitud {longitud_rectangulo} y ancho {ancho_rectangulo}:")
    print(f"El área del rectángulo es: {area_rectangulo:.2f} unidades cuadradas")
    print(f"El perímetro del rectángulo es: {perimetro_rectangulo:.2f} unidades")

    # Ejemplo de uso de tipo de dato entero (aunque no estrictamente necesario para esta tarea)
    # numero_intentos = 1 # Si hubiéramos implementado un contador de intentos.
    # print(f"Este cálculo se realizó en {numero_intentos} intento(s).")

# Llamar a la función principal para ejecutar el programa
if __name__ == "__main__":
    calcular_dimensiones_rectangulo()